language: python

python:
  - "3.5"

sudo: false
cache: pip

addons:
  postgresql: "9.6"
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml  # because pip installation is slow

env:
  global:
  - VERSION="12.0" TESTS="0" LINT_CHECK="0" TRANSIFEX="0"
  - TRANSIFEX_USER='transbot@odoo-community.org'
  - secure: FFyWAwM7PmCbOI8lSIFNkDknkspQQv3sD8aKyz5tTPtAmLdALEj+MaPsuZJS9PoHzqjrylrhHEg+lB5lNjHR+3t2oOgHZb44l+mob22N6WDB5nag11jnBI+q0hGEHrbYNe5r3mnNvUQKXSfmjyKE181755fnOvhc88x5DnHXo0Q=
  
  matrix:
  - LINT_CHECK="1"
  - TRANSIFEX="1"
  - TESTS="1" ODOO_REPO="OCA/OCB"
  - TESTS="1" ODOO_REPO="odoo/odoo"


install:
  - pip install unicodecsv
  - git clone --depth=1 https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - git clone --depth=1 https://github.com/OCA/partner-contact.git ${HOME}/partner-contact
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly
# example: dependency
  - git clone --depth=1 https://github.com/OCA/web -b ${VERSION} $HOME/web

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
